/**
 * Every user-visible English string in one place, so the app can be
 * translated later without hunting through components.
 */
export const strings = {
  appTitle: "L.S.Design Studio",
  toolbar: {
    zoomFitAll: "Fit all",
    zoomActual: "100%",
    resetLayout: "Reset layout",
    panelToggleShow: "Show panel",
    panelToggleHide: "Hide panel",
    deviceAll: "All devices",
    deviceDesktop: "Desktop",
    deviceTablet: "Tablet",
    deviceMobile: "Mobile",
    decisionAll: "All",
    decisionPending: "Pending",
    decisionApproved: "Approved",
    decisionRejected: "Rejected",
    exportHandoff: "Export handoff",
    online: "Live",
    offline: "Offline",
    reconnecting: "Reconnecting…",
  },
  status: {
    draft: "Draft",
    direction: "Direction",
    screens: "Screens",
    approved: "Approved",
    built: "Built",
  },
  screenCard: {
    supersedes: (n: number) => `r${n} supersedes r${n - 1}`,
    staleTokens: "Stale tokens",
    revisionBadge: (n: number) => `r${n}`,
    staticPreview: "Static preview",
    liveToggleOn: "Live",
    liveToggleOff: "PNG",
  },
  decision: {
    approve: "Approve",
    reject: "Reject",
    notesLabel: "Notes",
    notesPlaceholder: "Why is this rejected?",
    followUp: "Follow-up action",
    followUpNone: "None",
    followUpRegenerate: "Regenerate",
    followUpEdit: "Edit with prompt",
    followUpVariants: "Variants",
    submit: "Submit",
    cancel: "Cancel",
    promptLabel: "Prompt",
    promptPlaceholder: "Describe the change…",
  },
  tabs: {
    board: "Board",
    review: "Review",
    tokens: "Tokens",
    label: "Studio sections",
  },
  canvas: {
    emptyFiltered: "No screens match this filter. Set both filters back to \u201cAll\u201d to see the board.",
  },
  review: {
    heading: "Review",
    empty: "No screens yet.",
    showOnCanvas: "Show on canvas",
    openFull: "Open full size",
    states: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
    },
    notesLabel: "Your notes",
    changeLabel: "Ask for a change",
    changePlaceholder: "Describe what you want different \u2014 e.g. \u201cmake the hero headline smaller and move the product image left\u201d",
    changeSubmit: "Request change",
    changeSent: "Queued. The agent picks this up and returns a new revision.",
  },
  requestQueue: {
    heading: "Requests",
    empty: "No requests yet.",
    cancel: "Cancel",
    type: "Type",
    target: "Target",
    age: "Age",
    state: "State",
    states: {
      pending: "Pending",
      claimed: "Claimed",
      done: "Done",
      failed: "Failed",
      cancelled: "Cancelled",
    },
  },
  tokenPanel: {
    heading: "Design tokens",
    colors: "Colors",
    rounded: "Rounded",
    spacing: "Spacing",
    save: "Save",
    regenerating: "Regenerating…",
    saved: "Saved",
    queueReapply: "Reapply to existing screens",
  },
  contrastTable: {
    heading: "Contrast",
    light: "Light",
    dark: "Dark",
    pair: "Pair",
    ratio: "Ratio",
    target: "Target",
    level: "Level",
    pass: "Pass",
    fail: "Fail",
  },
  gateBanner: {
    ready: "Ready to export",
    blocked: "Export blocked",
    pending: (n: number) => `${n} pending`,
    rejected: (n: number) => `${n} rejected`,
    stale: (n: number) => `${n} stale`,
    reapply: (n: number) => `${n} reapplications queued`,
    forceExport: "Force export",
    forceExportConfirm: "Export anyway even though the gate has not passed?",
  },
  errors: {
    loadFailed: "Failed to load the studio state.",
    revConflict: "Someone else changed this. Please retry.",
    generic: "Something went wrong.",
  },
} as const;
